### ISSUE TITLE
Proposal to implement GitFlow branch workflow.

### ISSUE THREAD

**Issue by bradyzp** [DynamicGravitySystems/DGP#14]
For consideration, proposing to adopt the GitFlow branching/workflow scheme as detailed here:
http://nvie.com/posts/a-successful-git-branching-model/

This would require us to ideally merge all existing code into master and then create a develop branch from which all future feature branches would then originate.

**Comment by cbertinato** [comment]
I like this model. Let's work toward tying up any of the open branches.

**Comment by bradyzp** [comment]
Project has been migrated.
