### ISSUE TITLE
Complete functionality for graphical selection of lines within a flight.

### ISSUE THREAD

**Issue by cbertinato** [DynamicGravitySystems/DGP#20]
- [x] Make rectangles resizable.
- [x] Translate rectangle bounds to datetimes.
- [x] Make rectangles removable.
- [x] Integrate with GUI.
- [x] Load saved lines on project load/start.

**Comment by cbertinato** [comment]
Potential requirements for behavior and user interaction for line selection: 
- Line labels show up on selection rectangles.
- Some sort of list view either in project tree, or separate window, or both, showing line name and time     bounds.
- Set rectangle bounds in list view.
- When resizing rectangles, select a rectangle by double-clicking, changing the rectangle color to indicate that it is selected.

**Comment by bradyzp** [comment]
Some ideas in regards to the line selection:

- User could select the lines by pressing a 'capture' button in the interface, after they have placed and resized rectangles specifying the start/stop of each line.
- Resizing rectangles: I like the double-click selection, and then possibly a click-drag on either side of the rectangle to resize it on the x-axis. Additionally we could maybe add a dialog or spin box that would allow the user to precisely specify or nudge the left/right bounds of the selected rectangle.
- Once the lines have been selected/captured I would then add them as sub-items to the flight they belong to in the project tree view. Possible functionality there would be to plot only the line data on a new plot when selected.
- Another idea would be to create a plot window that can be launched from the main interface, if we wanted to say see the plots of 2 or more flight-lines side by side. This could be useful in other areas too, for instance launching a new plot with a channel selection mechanism, allowing the user to select and plot any/all channels of the gravity/GPS data for QC.

**Comment by cbertinato** [comment]
Basic functionality implemented in merge commit #34. Remaining primary feature to be implemented is labeling for which a separate issue has been created.
