### ISSUE TITLE
BUG: Patches placed when zoomed to not resize when plot returns to original extent.

### ISSUE THREAD

**Issue by cbertinato** [DynamicGravitySystems/DGP#37]
Rectangle height is determined by y-axis limits at the time of creation. If a plot is zoomed when a patch is created, then when the graph returns to the original extents the patches do not cover the entire y extent of the graph.

**Comment by bradyzp** [comment]
This issue is further complicated with issue #36 as adding/removing channels can drastically change the plots Y limit, leaving the rectangles at a fraction of the height of the re-scaled plot.

**Comment by cbertinato** [comment]
Addressed in PR #45, but waiting to close this issue until implementation of the second y-axis is finished.
