### ISSUE TITLE
BUG: Error on line rectangle drag if no label set.

### ISSUE THREAD

**Issue by bradyzp** [DynamicGravitySystems/DGP#46]
Encountered error on current Develop branch with new line label code - if a Flight Line rectangle is placed and subsequently clicked or dragged, without first setting a label - an AttributeError is raised.

**Cause:**
line 404-405: dgp/lib/plotter.py: 
```python
label = attrs['label']
label.set_animated(True)  # Raises AttributeError: 'NoneType' object has no attribute 'set_animated'
```

**Resolution:**
Should be a simple case of checking that label is not None.

**Comment by cbertinato** [comment]
Fixed in PR #47
