### ISSUE TITLE
ENH: Clean-up code in LineGrabPlot

### ISSUE THREAD

**Issue by cbertinato** [DynamicGravitySystems/DGP#48]
- Evaluate whether picker interface is more efficient
- Work on modularity
- Work on speed

**Comment by bradyzp** [comment]
I'm going to start some work related to this feature, as I think it will be useful for the Transform tab interface.

Specifically to re-implement the graphical decimation routines to improve speed when interacting with the charts. 

Also to improve the modularity of the code as it comes to adding/removing sub-plots; with some possible work towards adding the Twin-Y axes scales.

Goals
------
- [x] Enable graphical decimation
- [x] Enable dynamic addition/removal of sub-plots
- [x] Implement Twin-Y axis on plots/sub-plots.

**Comment by bradyzp** [comment]
Resolved in PR #53 
Future improvements to be tracked in separate issues.
