### ISSUE TITLE
Tab/Plot Interface Redesign

### ISSUE THREAD

**Issue by bradyzp** [DynamicGravitySystems/DGP#50]
Some improvements I would like to make to the overall interface - focusing on the plot area and the tabs that are currently unused:

---
**Ideas/Proposals:**
1. Utilize the tabs: Treat each flight as a separate entity that can be opened in its own tab by dbl clicking, and then easily switched between or closed out of the work-space.
2. Multiple tabs per flight for different functions: Transform workspace, GPS/Map plot etc. Tabs for these functions could be opened via context menu (right click), or button in the workspace.
3. Possibly ability to drag tab out into new window, to make use of multiple screens, compare flights side by side etc.
4. Context menu for tabs - allow user to pop-out window, close, duplicate, etc.

**Comment by cbertinato** [comment]
I think all of these are good and should to some extent all be used in one way or another.  In terms of requirements, I think we should be able to do the following:
- Work on multiple flights at once
- Work on multiple projects at once (an entirely new parent window might suffice)
- Work on multiple screens

We will certainly need to figure out how to declutter the workspace with transforms, line picking, and maps, and tabs may be a good way to do that.  Does this mean something like tabs within tabs?  I like the idea of being able to pull a tab out to make a new child window.
