### ISSUE TITLE
Crash on deletion of flight

### ISSUE THREAD

**Issue by cbertinato** [DynamicGravitySystems/DGP#73]
There were two flights in the project.  I believe the first one was selected.  The second flight was empty, which is to say, it had no datasets associated.  I used the context menu to delete the second flight.  Here's the traceback:
```
Traceback (most recent call last):
  File "/Users/cbertinato/Documents/Git/DGP/dgp/core/controllers/flight_controller.py", line 89, in <lambda>
    lambda: self.get_parent().remove_child(self.uid, True))),
  File "/Users/cbertinato/Documents/Git/DGP/dgp/core/controllers/project_controllers.py", line 158, in remove_child
    raise ValueError("{0!r} is not a valid child object".format(child))
ValueError: <OID [Flight 2]-flight_be7585ceca4b4f84b4b64482be6e1edd> is not a valid child object
```

**Comment by bradyzp** [comment]
I see what's going on here, I apparently neglected to update the flight's remove-child action after changing the signatures around in the project controller.
I'll push a fix for this up later, and see If I can actually get some test coverage on the controller menu actions - I think it should be doable to test even the actions with confirmation using QTest.
